
name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 * * *"

jobs:
  test-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Futhark
      run: |
        wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
        tar xf futhark-nightly-linux-x86_64.tar.xz
        (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
        echo "::add-path::$HOME/.local/bin"
    - run: futhark pkg upgrade
    - run: futhark pkg sync
    - run: futhark test lib/
    - run: futhark test tests/
